# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03dc599eec70ae35bf8425db8b5521cc3d0888cf540e597812c50f5539b81007b4b97933476ee8e8e55155d69f87283cc8297b347d3d70b0dbb3335144b9c321

test:
  secret_key_base: aad983ed2bbf8afae216854631d9fc44bb7f5db0daa0ce0d3c3038920fbe48700ea2d8e81e4122cfebc735e3292c80c0b24862b7a267481683f74407af0e40f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
